---
name: Build and Push OR check-PR

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "**.yml"
      - "**.h"
      - "**.cpp"
      - "**.py"
      - "**.html"
      - "**.css"
      - "**.js"
      - "**.ini"
      - "**.json"
      - "**.csv"

  workflow_dispatch:

jobs:
  compile_sketch:
    name: Build ${{ matrix.board.name }}
    runs-on: ubuntu-latest
    
       strategy:
      fail-fast: false
      matrix:
        board:
          # Оставляем только те окружения, которые соответствуют вашему чипу ESP32-S3
          - { env: "m5stack-cardputer",               family: "ESP32-S3",}
          - { env: "esp32-s3-devkitc-1",              family: "ESP32-S3",}
          - { env: "lilygo-t-display-s3",             family: "ESP32-S3",}

    steps:
      - uses: actions/checkout@v4.2.2

      - id: build
        name: setup Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.13"

      - name: Install build deps (multilib)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gcc-multilib libc6-dev-i386

      # Кэширование PlatformIO для ускорения сборки в 10 раз (совместимо с Node 24)
      - name: Cache PlatformIO
        uses: actions/cache@v4.2.0
        with:
          path: |
            ~/.platformio
            ${{ github.workspace }}/.pio
          key: pio-${{ matrix.board.env }}-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            pio-${{ matrix.board.env }}-

      # Tar-файлы кэша pip (ИСПРАВЛЕНО: добавлена решётка в начале строки)
      - name: Cache Pip
        uses: actions/cache@v4.2.0
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}

      - name: Install PlatformIO Core
        run: |
          pip install platformio requests esptool intelhex

          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            version=${{ github.ref_name }}
          else
            version="${GITHUB_SHA::7}"
          fi

          sed -i "s/-DBRUCE_VERSION=/-DBRUCE_VERSION='\"$version\"' ; /g" ./platformio.ini
          sed -i "s/-DGIT_COMMIT_HASH='\"Homebrew\"'/\!echo '-DGIT_COMMIT_HASH=\\\\\\\\\"'\$\(git describe --always --dirty)'\\\\\\\\\"'/g" ./platformio.ini

          cat ./platformio.ini

      - name: Run Compile
        run: |
          platformio run -e ${{ matrix.board.env }}

      - name: Upload ${{ matrix.board.name }}
        uses: actions/upload-artifact@v4
        with:
          name: Bruce-${{ matrix.board.env }}
          path: .pio/build/${{ matrix.board.env }}/firmware.bin
          retention-days: 5
          if-no-files-found: error
